### ISSUE TITLE
Buzzing vent above staircase

### ISSUE THREAD

**Issue by cmwinters** [cmwinters/santa-crew#2]
The vent above the staircase has been buzzing nonstop for the past week. It's annoying. I say we contact Al and get him to fix it. Thoughts?

**Comment by tdhartwick** [comment]
I'm thinking about shutting off power to that area of the house via the circuit breaker, and opening it up. Will try to tighten anything and just look at.

I want to do this sometime this week. But we should probably call Al regardless to get it looked at.

Assigning to myself to open 'er up!

**Comment by mrsweaters** [comment]
I'm marking this issue resolved, even if we no longer have a doorbell.
